courses/grails-app/domain/courses/Country.groovy
package courses

class Country {

    Integer id
    String name
    String region
    String citizenship
    Boolean deleted = false

    static hasMany = [studentsForCitizenship: Student,
                      studentsForCountryOfProvenance: Student,
                      universities: University]

    static mappedBy = [studentsForCitizenship: "citizenship",
                       studentsForCountryOfProvenance: "countryOfProvenance"]

    static mapping = {
        table "countries"
        id column: "country_ID", generator: "native"
        version false
    }

    static constraints = {
        name unique: true, blank: false
        region maxSize: 200
    }

    static namedQueries = {
        notDeleted {
            ne 'deleted', true
        }
    }

    String toString() { "${this.class.name} : $id - $name" }
}

courses/grails-app/domain/courses/Course.groovy
package courses

class Course {

    Integer id
    String notes
    Date actualStartDate
    String institution
    String place
    Integer credits
    String courseName
    Integer academicYear = 2012
    Boolean isInManifesto = false
    Boolean isByUnitn = false
    Boolean isPaid = false
    Integer budgetedCost = 0
    Integer actualCost = 0
    String plannedCoursePeriod
    Boolean areAllMarksDefined = false
    String url
    Boolean isPaymentCompleted = false
    Boolean deleted = false
    Supervisor professor

    static hasMany = [coursesEnrollments: CourseEnrollment]
    static belongsTo = [Supervisor]

    static mapping = {
        table "courses"
        id column: "course_ID"
        notes type: 'text'
        professor column: "professor"
        version false

    }

    static constraints = {
        courseName blank: false

        notes nullable: true, maxSize: 65535
        actualStartDate nullable: true, maxSize: 10
        professor nullable: true
        credits nullable: true
        courseName maxSize: 200
        isPaid nullable: true
    }

    static namedQueries = {
        notDeleted {
            ne 'deleted', true
        }
    }

    String toString() { "${this.class.name} : $id" }
}

courses/grails-app/controllers/courses/CountryController.groovy
package courses

import org.springframework.dao.DataIntegrityViolationException

class CountryController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    /**
     * Index: redirects to list
     */
    def index() {
        redirect(action: "list", params: params)
    }

    /**
     * Lists all countries
     */
    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        def countries = Country.notDeleted.list(params)
        [countryInstanceList: countries,
         countryInstanceTotal: Country.notDeleted.count()]
    }

    /**
     * Create form for a new country
     */
    def create() {
        [countryInstance: new Country(params)]
    }

    /**
     * Saves the new country (accepts POST)
     */
    def save() {
        def countryInstance = new Country(params)
        if (!countryInstance.save(flush: true)) {
            render(view: "create", model: [countryInstance: countryInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'country.label', default: 'Country'), countryInstance.id])
        redirect(action: "show", id: countryInstance.id)
    }

    /**
     * Shows the country with the given id
     */
    def show() {
        def countryInstance = Country.get(params.id)
        if (!countryInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'country.label', default: 'Country'), params.id])
            redirect(action: "list")
            return
        }

        [countryInstance: countryInstance]
    }

    /**
     * Edit form for the country with the given id
     */
    def edit() {
        def countryInstance = Country.get(params.id)
        if (!countryInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'country.label', default: 'Country'), params.id])
            redirect(action: "list")
            return
        }

        [countryInstance: countryInstance]
    }

    /**
     * Update the country with the given id (accepts POST)
     */
    def update() {
        def countryInstance = Country.get(params.id)
        if (!countryInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'country.label', default: 'Country'), params.id])
            redirect(action: "list")
            return
        }

        if (params.version) {
            def version = params.version.toLong()
            if (countryInstance.version > version) {
                countryInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'country.label', default: 'Country')] as Object[],
                          "Another user has updated this Country while you were editing")
                render(view: "edit", model: [countryInstance: countryInstance])
                return
            }
        }

        countryInstance.properties = params

        if (!countryInstance.save(flush: true)) {
            render(view: "edit", model: [countryInstance: countryInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'country.label', default: 'Country'), countryInstance.id])
        redirect(action: "show", id: countryInstance.id)
    }

    /**
     * Soft-deletes a country (accepts POST)
     */
    def delete() {
        def countryInstance = Country.get(params.id)
        if (!countryInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'country.label', default: 'Country'), params.id])
            redirect(action: "list")
            return
        }

        try {
            countryInstance.deleted = true
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'country.label', default: 'Country'), params.id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'country.label', default: 'Country'), params.id])
            redirect(action: "show", id: params.id)
        }
    }
}

courses/grails-app/views/country/_form.gsp
<div class="control-group ${hasErrors(bean: countryInstance, field: 'name', 'error')} ">
  <label class="control-label"for="name">
    <g:message code="country.name.label" default="Name" />
  </label>
  <div class="control">
    <g:textField name="name" value="${countryInstance?.name}"/>
  </div>
</div>

<div class="control-group ${hasErrors(bean: countryInstance, field: 'region', 'error')} ">
  <label class="control-label"for="region">
    <g:message code="country.region.label" default="Region" />
  </label>
  <div class="control">
    <g:textField name="region" maxlength="200" value="${countryInstance?.region}"/>
  </div>
</div>

<div class="control-group ${hasErrors(bean: countryInstance, field: 'citizenship', 'error')} ">
  <label class="control-label"for="citizenship">
    <g:message code="country.citizenship.label" default="Citizenship" />
  </label>
  <div class="control">
    <g:textField name="citizenship" value="${countryInstance?.citizenship}"/>
  </div>
</div>


<g:if test="${countryInstance.id}">
  <div class="control-group ${hasErrors(bean: countryInstance, field: 'studentsForCitizenship', 'error')} ">
    <label class="control-label"for="studentsForCitizenship">
      <g:message code="country.studentsForCitizenship.label" default="Students For Citizenship" />
    </label>
    <div class="control">

      <ul class="one-to-many">
        <g:each in="${countryInstance?.studentsForCitizenship?}" var="s">
          <li>
            <g:link controller="student" action="show" id="${s.id}">
              ${s?.firstName?.encodeAsHTML()}
              ${s?.lastName?.encodeAsHTML()}
            </g:link>
          </li>
        </g:each>
        <li class="add">
          <g:link controller="student" action="create" params="['country.id': countryInstance?.id]">
            ${message(code: 'default.add.label', args: [message(code: 'student.label', default: 'Student')])}
          </g:link>
        </li>
      </ul>
    </div>
  </div>

  <div class="control-group ${hasErrors(bean: countryInstance, field: 'studentsForCountryOfProvenance', 'error')} ">
    <label class="control-label"for="studentsForCountryOfProvenance">
      <g:message code="country.studentsForCountryOfProvenance.label" default="Students For Country Of Provenance" />
    </label>
    <div class="control">
      <ul class="one-to-many">
        <g:each in="${countryInstance?.studentsForCountryOfProvenance?}" var="s">
          <li>
            <g:link controller="student" action="show" id="${s.id}">
              ${s?.firstName?.encodeAsHTML()}
              ${s?.lastName?.encodeAsHTML()}
            </g:link>
          </li>
        </g:each>
        <li class="add">
          <g:link controller="student" action="create" params="['country.id': countryInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'student.label', default: 'Student')])}</g:link>
        </li>
      </ul>
    </div>
  </div>

  <div class="control-group ${hasErrors(bean: countryInstance, field: 'universities', 'error')} ">
    <label class="control-label"for="universities">
      <g:message code="country.universities.label" default="Universities" />

    </label>
    <div class="control">
      <ul class="one-to-many">
        <g:each in="${countryInstance?.universities?}" var="u">
          <li>
            <g:link controller="university" action="show" id="${u.id}">
              ${u?.nameUniversity?.encodeAsHTML()}
            </g:link>
          </li>
        </g:each>
        <li class="add">
          <g:link controller="university" action="create" params="['country.id': countryInstance?.id]">
            ${message(code: 'default.add.label', args: [message(code: 'university.label', default: 'University')])}
          </g:link>
        </li>
      </ul>
    </div>
  </div>
</g:if>

<script type="text/javascript">
  menu_active("#menu_country");
</script>

courses/grails-app/views/country/create.gsp
<g:applyLayout name="base">

  <content tag="title">
    <g:message code="country.create.title" default="Create new country" />
  </content>

  <content tag="container">
    <h2><g:message code="country.create.title" default="Create new country" /></h2>

    <g:if test="${flash.message}">
      <div class="alert alert-info" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${countryInstance}">
      <ul class="alert alert-error" role="alert">
        <g:eachError bean="${courseInstance}" var="error">
          <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
            <g:message error="${error}"/>
          </li>
        </g:eachError>
      </ul>
    </g:hasErrors>


    <g:form class="form-horizontal" action="save" >
      <fieldset class="form">
        <g:render template="form"/>
      </fieldset>
      <fieldset class="form-actions">
        <g:submitButton class="btn btn-success save" name="create" value="${message(code: 'default.button.create.label', default: 'Create')}" />
      </fieldset>
    </g:form>

  </content>

</g:applyLayout>

courses/grails-app/views/country/edit.gsp
<g:applyLayout name="base">

  <content tag="container">
    <h2><g:message code="country.edit.title" default="Edit country" /></h2>

    <g:if test="${flash.message}">
      <div class="alert alert-info" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${countryInstance}">
      <ul class="alert alert-error" role="alert">
        <g:eachError bean="${courseInstance}" var="error">
          <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
            <g:message error="${error}"/>
          </li>
        </g:eachError>
      </ul>
    </g:hasErrors>


    <g:form method="post" class="form-horizontal">
      <g:hiddenField name="id" value="${countryInstance?.id}" />
      <g:hiddenField name="version" value="${countryInstance?.version}" />
      <fieldset>
        <g:render template="form"/>
        <div class="form-actions">
          <g:actionSubmit class="btn btn-success save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
          <g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
        </div>
      </fieldset>
    </g:form>

  </content>

</g:applyLayout>

courses/grails-app/views/country/list.gsp
<g:applyLayout name="base">
  <content tag="container">

    <g:link action='create'>
      <button class="btn btn-success">
        <i class="icon-plus-sign icon-white"></i>
        <g:message code="country.nav.new" default="New Country" />
      </button>
    </g:link>
    <hr/>

    <div id="list-country" class="content" role="main">
      <g:if test="${flash.message}">
      <div class="alert alert-info" role="status">${flash.message}</div>
      </g:if>
      <table class="table table-striped">
        <thead>
          <tr>

            <g:sortableColumn property="name" title="${message(code: 'country.name.label', default: 'Name')}" />

            <g:sortableColumn property="region" title="${message(code: 'country.region.label', default: 'Region')}" />

            <th>
              <a href="#"><g:message code='country.edit.label' default='Edit' /></a>
            </th>

          </tr>
        </thead>
        <tbody>
        <g:each in="${countryInstanceList}" status="i" var="countryInstance">
          <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

            <td>
              <g:link action="show" id="${countryInstance.id}">
                ${fieldValue(bean: countryInstance, field: "name")}
              </g:link>
            </td>

            <td>${fieldValue(bean: countryInstance, field: "region")}</td>

            <td>
              <g:link action="edit" id="${countryInstance.id}">
                <i class="icon-pencil"></i>
              </g:link>
            </td>

          </tr>
        </g:each>
        </tbody>
      </table>
      <div class="pagination">
        <g:paginate total="${countryInstanceTotal}" />
      </div>
      <script type="text/javascript">
        menu_active("#menu_country");
      </script>
  </content>
</g:applyLayout>

courses/grails-app/views/country/show.gsp
<g:applyLayout name="base">

  <content tag="container">

    <div id="show-country" class="content scaffold-show" role="main">
      <h1><g:message code="country.show.title" default="Show country" /></h1>
      <g:if test="${flash.message}">
      <div class="alert alert-info" role="status">${flash.message}</div>
      </g:if>
      <ol class="property-list country">

        <g:if test="${countryInstance?.name}">
        <li class="fieldcontain">
          <span id="name-label" class="property-label"><g:message code="country.name.label" default="Name" /></span>

            <span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${countryInstance}" field="name"/></span>

        </li>
        </g:if>

        <g:if test="${countryInstance?.region}">
        <li class="fieldcontain">
          <span id="region-label" class="property-label"><g:message code="country.region.label" default="Region" /></span>

            <span class="property-value" aria-labelledby="region-label"><g:fieldValue bean="${countryInstance}" field="region"/></span>

        </li>
        </g:if>

        <g:if test="${countryInstance?.citizenship}">
        <li class="fieldcontain">
          <span id="citizenship-label" class="property-label"><g:message code="country.citizenship.label" default="Citizenship" /></span>

            <span class="property-value" aria-labelledby="citizenship-label"><g:fieldValue bean="${countryInstance}" field="citizenship"/></span>

        </li>
        </g:if>

        <g:if test="${countryInstance?.studentsForCitizenship}">
        <li class="fieldcontain">
          <span id="studentsForCitizenship-label" class="property-label"><g:message code="country.studentsForCitizenship.label" default="Students For Citizenship" /></span>

            <g:each in="${countryInstance.studentsForCitizenship}" var="s">
              <span class="property-value" aria-labelledby="studentsForCitizenship-label">
                <g:link controller="student" action="show" id="${s.id}">
                  ${s?.firstName?.encodeAsHTML()}
                  ${s?.lastName?.encodeAsHTML()}
                </g:link>
              </span>
            </g:each>

        </li>
        </g:if>

        <g:if test="${countryInstance?.studentsForCountryOfProvenance}">
        <li class="fieldcontain">
          <span id="studentsForCountryOfProvenance-label" class="property-label"><g:message code="country.studentsForCountryOfProvenance.label" default="Students For Country Of Provenance" /></span>

            <g:each in="${countryInstance.studentsForCountryOfProvenance}" var="s">
              <span class="property-value" aria-labelledby="studentsForCountryOfProvenance-label">
                <g:link controller="student" action="show" id="${s.id}">
                  ${s?.firstName?.encodeAsHTML()}
                  ${s?.lastName?.encodeAsHTML()}
                </g:link>
              </span>
            </g:each>

        </li>
        </g:if>

        <g:if test="${countryInstance?.universities}">
        <li class="fieldcontain">
          <span id="universities-label" class="property-label"><g:message code="country.universities.label" default="Universities" /></span>

            <g:each in="${countryInstance.universities}" var="u">
              <span class="property-value" aria-labelledby="universities-label">
                <g:link controller="university" action="show" id="${u.id}">
                  ${u?.nameUniversity?.encodeAsHTML()}
                </g:link>
              </span>
            </g:each>

        </li>
        </g:if>

      </ol>
      <g:form>
        <fieldset class="buttons">
          <g:hiddenField name="id" value="${countryInstance?.id}" />
          <g:link class="btn btn-primary" action="edit" id="${countryInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
          <g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
        </fieldset>
      </g:form>
    </div>

    <script type="text/javascript">
      menu_active("#menu_country");
    </script>
  </content>

</g:applyLayout>