courses/grails-app/controllers/courses/AdminController.groovy
package courses

class AdminController {

    /**
     * Index page: redirects to home
     */
    def index() {
        redirect(action: "home", params: params)
    }

    /**
     * Admin home page: displays some stats and other general info
     */
    def home() {
        def num_courses = Course.notDeleted.count()
        def num_courses_paid = Course.notDeleted.findAllByIsPaid(true).size()
        def num_courses_byUnitn = Course.notDeleted.findAllByIsByUnitn(true).size()
        def courses_more_costs = Course.notDeleted.list(max: 3, sort: "actualCost", order: "desc")


        def num_students = Student.notDeleted.count()
        def num_students_admittedConditionally = Student.notDeleted.findAlladmittedConditionally(true).size()
        def num_students_graduated = Student.notDeleted.findAllIsGraduated(true).size()

        def num_supervisors = Supervisor.notDeleted.count()
        def num_supervisors_internal = Supervisor.notDeleted.findAllIsInternal(true).size()
        def num_supervisors_external = Supervisor.notDeleted.findAllIsInternal(false).size()
        def num_supervisors_active = Supervisor.notDeleted.findAllIsActive(true).size()

        [
            num_courses: num_courses,
            num_courses_paid: num_courses_paid,
            num_courses_byUnitn:num_courses_byUnitn,
            courses_more_costs : courses_more_costs,
            //courses_more_enrollments : courses_more_enrollments,

            num_students: num_students,
            num_students_admittedConditionally : num_students_admittedConditionally,
            num_students_graduated : num_students_graduated,

            num_supervisors : num_supervisors,
            num_supervisors_internal : num_supervisors_internal,
            num_supervisors_external : num_supervisors_external,
            num_supervisors_active : num_supervisors_active
        ]
    }
}

courses/grails-app/views/layouts/_footer.gsp
<p class="footer">
  &copy; DEViati team 2012
</p>

courses/grails-app/views/layouts/_menubar.gsp
 <g:if test="${session.isAdmin}">
  <li class="nav-header">
    <g:message code="admin.menu.header" />
  </li>
  <li id="menu_home">
    <g:link controller="admin" action="home"><g:message code="admin.menu.home"/></g:link>
  </li>
  <li class="nav-header">
    <g:message code="admin.menu.header.students" />
  </li>
  <li id="menu_students">
    <g:link controller="student" action="list"><g:message code="admin.menu.students"/></g:link>
  </li>
  <li id="menu_study_plans">
    <g:link controller="student" action="list_incorrect_studyplans"><g:message code="admin.menu.study_plans"/></g:link>
  </li>
  <li class="nav-header">
    <g:message code="admin.menu.header.courses" />
  </li>
  <li id="menu_courses">
    <g:link controller="course" action="list"><g:message code="admin.menu.courses"/></g:link>
  </li>
  <li class="nav-header">
    <g:message code="admin.menu.header.professors" />
  </li>
  <li id="menu_professors">
    <g:link controller="supervisor" action="list"><g:message code="admin.menu.professors"/></g:link>
  </li>
  <li class="nav-header">
    <g:message code="admin.menu.header.other" />
  </li>
  <li id="menu_country">
    <g:link controller="country" action="list"><g:message code="admin.menu.country" /></g:link>
  </li>
  <li id="menu_university">
    <g:link controller="university" action="list"><g:message code="admin.menu.university" /></g:link>
  </li>
</g:if>
<g:elseif test="${session.isStudent}">
  <li class="nav-header">
    <g:message code="student.menu.header"/>
  </li>
  <li id="menu_home">
    <g:link controller="student" action='home'><g:message code="student.menu.home.home"/></g:link>
  </li>
  <li class="nav-header">
    <g:message code="student.menu.header.studyplan"/>
  </li>
  <li id="menu_planned_exams">
    <g:link controller="student" action='planned_exams'><g:message code="student.menu.studyplan.planned_exams"/></g:link>
  </li>
  <li id="menu_past_exams">
    <g:link controller="student" action='past_exams'><g:message code="student.menu.studyplan.past_exams"/></g:link>
  </li>
  <li id="menu_studyplan">
    <g:link controller="student" action='study_plan'><g:message code="student.menu.studyplan.study_plan"/></g:link>
  </li>
  <li class="nav-header">
    <g:message code="student.menu.header.courses"/>
  </li>
  <li id="menu_courses">
    <g:link controller="course" action="list_student"><g:message code="student.menu.courses.available_courses"/></g:link>
  </li>
</g:elseif>
<g:elseif test="${session.isSupervisor}">
  <li class="nav-header">
    <g:message code="supervisor.menu.header"/>
  </li>
  <li id="menu_home">
    <g:link controller="supervisor" action="home"><g:message code="supervisor.menu.home" /></g:link>
  </li>
  <li class="nav-header">
    <g:message code="supervisor.menu.header.profile"/>
  </li>
  <li id="menu_profile">
    <g:link controller="supervisor" action="show" id="${session.user.id}"><g:message code="supervisor.menu.profile" /></g:link>
  </li>
  <li class="nav-header">
    <g:message code="supervisor.menu.header.courses"/>
  </li>
  <li id="menu_courses">
    <g:link controller="course" action="list_supervisor"><g:message code="supervisor.menu.courses" /></g:link>
  </li>
</g:elseif>

courses/grails-app/views/layouts/_navbar.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#"><g:message code="navbar.header" default="Courses Management"/></a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Team</a></li>
        </ul>

        <ul class="nav pull-right">
          <li><a id="i18n-en" href=".?lang=en">EN</a></li>
          <li><a id="i18n-it" href=".?lang=it">IT</a></li>
          <li class="dropdown" id="menu1">
            <g:if test="${!session.user}">
              <a id="login" class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
                Login
                <b class="caret"></b>
              </a>
              <div class="dropdown-menu">
                <br/>
                <input id="email" type="text" placeholder="email" />
                <input id="password" type="password" placeholder="password" />
                <div class='btn btn-primary'>Login</div>
                <div><a href="#"><g:message code="default.index.navbar" default="Forgot your password?"/></a></div>
              </div>
            </g:if>
            <g:else>
              <g:link url="[action: 'logout', controller: 'userCredential']">
                Logout
              </g:link>
            </g:else>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

courses/grails-app/views/layouts/base.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="layout" content="page"/>
    <title><g:pageProperty name="page.title"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <r:require modules="bootstrap"/>
    <r:require modules="bootstrap-modal"/>

    <g:javascript library="jquery"/>
    <g:javascript src="courses.js" />

    <resource:richTextEditor />

    <r:layoutResources/>

    <!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- COMPASS -->
    <link href="${resource(dir: 'css/sass', file: 'screen.css')}" media="screen, projection" rel="stylesheet" type="text/css" />
    <link href="${resource(dir: 'css/sass', file: 'print.css')}" media="screen, projection" rel="stylesheet" type="text/css" />

    <style>
       @font-face { font-family: Lobster2; src: url('${resource(dir: 'fonts/lobster-two', file: 'LobsterTwo-Regular.otf')}'); }
    </style>

    <!--[if IE]>
      <link href="${resource(dir: 'css/sass', file: 'ie.css')}" media="screen, projection" rel="stylesheet" type="text/css" />
    <![endif]-->

    <g:layoutHead/>

  </head>

  <body>

    <g:render template="/layouts/navbar"/>

    <div class="container-fluid">
      <div class="row-fluid">

        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">

              <g:render template="/layouts/menubar"/>

            </ul>
          </div>

        </div><!--/span-->

        <div class="span9">

          <g:pageProperty name="page.container"/>

        </div><!--/span-->
      </div><!--/row-->

      <hr>
      <g:render template="/layouts/footer"/>

    </div><!--/.fluid-container-->
  </body>
</html>

<r:layoutResources disposition="defer"/>

courses/grails-app/views/layouts/main.gsp
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
        <r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<g:javascript library="application"/>
        <r:layoutResources />
	</body>
</html>